function showToast(msg,type){var root=document.getElementById('toast-root');if(!root)return;var t=document.createElement('div');t.className='toast toast-'+(type||'success');t.textContent=msg;root.appendChild(t);requestAnimationFrame(function(){t.classList.add('toast-in');});setTimeout(function(){t.classList.remove('toast-in');t.classList.add('toast-out');setTimeout(function(){if(t.parentNode)t.parentNode.removeChild(t);},300);},3200);}
function saveData(){try{localStorage.setItem('nassRows',JSON.stringify(rows));localStorage.setItem('nassOfficers',JSON.stringify(officers));localStorage.setItem('nassStatuses',JSON.stringify(statuses));localStorage.setItem('nassLocations',JSON.stringify(locations));localStorage.setItem('nassActions',JSON.stringify(actions));localStorage.setItem('nassFileIndex',JSON.stringify(fileIndex));}catch(e){}}
function loadData(){try{var r=localStorage.getItem('nassRows');if(r)rows=JSON.parse(r);var o=localStorage.getItem('nassOfficers');if(o)officers=JSON.parse(o);var s=localStorage.getItem('nassStatuses');if(s)statuses=JSON.parse(s);var l=localStorage.getItem('nassLocations');if(l)locations=JSON.parse(l);var a=localStorage.getItem('nassActions');if(a)actions=JSON.parse(a);var fi=localStorage.getItem('nassFileIndex');if(fi)fileIndex=JSON.parse(fi);}catch(e){}}
function sc(s){var l=(s||'').toLowerCase();if(l==='active')return 's-active';if(l==='completed')return 's-completed';if(l==='on hold')return 's-hold';if(l==='cancelled')return 's-cancelled';if(l==='filed')return 's-filed';return '';}
function computeFlag(r){var status=(r[10]||'').toLowerCase();if(status==='completed'||status==='filed'||status==='cancelled')return'ON TIME';var due=r[9];if(!due||due.length<8){var sla=parseInt(r[8]);var dmov=r[7]||r[6];if(!isNaN(sla)&&sla>0&&dmov&&dmov.length>=8){var d=new Date(dmov);d.setDate(d.getDate()+sla);due=d.toISOString().split('T')[0];}}if(!due||due.length<8)return'';var today=new Date();today.setHours(0,0,0,0);var dueDate=new Date(due);dueDate.setHours(0,0,0,0);return dueDate<today?'OVERDUE':'ON TIME';}
function calcDueDate(dmov,sla){if(!dmov||dmov.length<8)return'';var s=parseInt(sla);if(isNaN(s)||s<=0)return'';var d=new Date(dmov);d.setDate(d.getDate()+s);return d.toISOString().split('T')[0];}
function updateModalDue(){var dmov=document.getElementById('m-dmov').value;var sla=document.getElementById('m-sla').value;var due=calcDueDate(dmov,sla);if(due)document.getElementById('m-due').value=due;}
function fmtDate(v){if(!v)return'';var p=v.split('-');if(p.length!==3)return v;return p[2]+'/'+p[1]+'/'+p[0];}function mkSel(list,val,cb){var s=document.createElement('select');var b=document.createElement('option');b.value='';b.textContent='—';s.appendChild(b);list.forEach(function(o){var op=document.createElement('option');op.value=o;op.textContent=o;if(o===val)op.selected=true;s.appendChild(op);});if(cb)s.addEventListener('change',cb);return s;}
function mkInp(val,type,cb){var i=document.createElement('input');i.type=type||'text';i.value=val||'';if(cb)i.addEventListener('change',cb);return i;}
function _esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}
function _hl(text,q){if(!q)return _esc(text);var esc=_esc(text);var re=new RegExp('('+q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+')','gi');return esc.replace(re,'<mark class="srch-hl">$1</mark>');}
